permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: oh_ouyang
  email: guo0625@hotmail.com
  weibo: http://weibo.com/1970890475/profile?topnav=1
  github: http://github.com/Guo0625
  music: http://site.douban.com/Oh_ouyang
  linkedin: https://www.linkedin.com

# 站点信息
title: oh_ouyang的博客
description: My personal blog
url: http://github.com/Guo0625
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.jpg
favicon: /public/img/deer3.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: http://github.com/Guo0625

# disqus 设置
disqus:
  shortname: oh-ouyang

# 主题设置，自动激活某个标签
active: Book

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: Tags
  about: 关于
  newest: 最新文章
  archive: 记录